### ISSUE TITLE
OverflowError: (34, 'Result too large')

### ISSUE THREAD

**Issue by penguinaugustus** [EmoryUniversityTheoreticalBiophysics/SirIsaac#31]
Hi, Professor Daniels,

I am trying to perform modelling mRMA network data with sigmoidal class. I created a fitting problem with 100 data point, after I run my program at terminal for approximately 100 minutes, the program ended with an overflow error:
```
***STDERR***
b"<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n"
localFitParallel: worker 1 working on work_array 0...
localFitParallel: worker 6 working on work_array 5...
localFitParallel: worker 7 working on work_array 6...
localFitParallel: worker 3 working on work_array 2...
localFitParallel: worker 8 working on work_array 7...
localFitParallel: worker 4 working on work_array 3...
localFitParallel: worker 9 working on work_array 8...
localFitParallel: worker 2 working on work_array 1...
WARNING:ReactionNetworks.Components:Failed to import dynamically compiled C module CTSN_0_wirelessprv_10_194_237_143_near_illinois_edu_78849_8762937861_48443 for network CTSN.
WARNING:ReactionNetworks.Components:No module named 'CTSN_0_wirelessprv_10_194_237_143_near_illinois_edu_78849_8762937861_48443'
localFitParallel: worker 5 working on work_array 4...
capi_return is NULL
Call-back cb_jac_in_daskr__user__routines failed.
Fatal Python error: F2PySwapThreadLocalCallbackPtr: PyLong_AsVoidPtr failed
Python runtime state: initialized
Traceback (most recent call last):
  File "<string>", line 6, in ddaskr_jac
  File "<string>", line 38, in dres_dc_function
OverflowError: (34, 'Result too large')

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 48442 RUNNING AT wirelessprv-10-194-237-143.near.illinois.edu
=   EXIT CODE: 6
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Abort trap: 6 (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

Traceback (most recent call last):
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fittingProblem.py", line 1823, in localFitToData_parallel
    output = load(outputFilename)
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/simplePickle.py", line 24, in load
    fin = io.open(filename,'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'temporary_94132_localFitToData_parallel_output.data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/penguinaugustus/Desktop/mrna_sig_terminal/mRNA-sigm.py", line 195, in <module>
    p.fitAll()
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fittingProblem.py", line 979, in fitAll
    FittingProblem.fitAll(self,**kwargs)
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fittingProblem.py", line 216, in fitAll
    fittingModel.fitToData(self.fittingData,self.indepParamsList,         \
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fittingProblem.py", line 1720, in fitToData
    outputDict = self.localFitToData_parallel(self.numprocs,fittingData,
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fittingProblem.py", line 1832, in localFitToData_parallel
    raise Exception("localFitToData_parallel:"                            \
Exception: localFitToData_parallel: error in localFitParallel.py

########### EXT COMPILER OPTIMIZATION ###########
Platform      : 
  Architecture: x64
  Compiler    : gcc

CPU baseline  : 
  Requested   : 'min'
  Enabled     : SSE SSE2 SSE3
  Flags       : -msse -msse2 -msse3
  Extra checks: none

CPU dispatch  : 
  Requested   : 'max -xop -fma4'
  Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
  Generated   : none
CCompilerOpt._cache_write[796] : write cache to path -> /Users/penguinaugustus/Desktop/mrna_sig_terminal/build/temp.macosx-10.9-x86_64-3.8/ccompiler_opt_cache_ext.py

```
Could you give me any hint on what may go wrong and how to fix it?

Thank you for your time!

Sincerely,
Yu

**Comment by bcdaniels** [comment]
Yu,

I’m currently traveling, so more detailed debugging will have to wait until next week.  You could try looking for a file `temporary_94132_localFitToData_parallel_stdout.txt` that might give more information. In general, these overflow errors tend to happen a lot when fitting models using SirIsaac, but in the ideal case the errors should be caught automatically. So there must still be a case where the error can slip through (sorry!).

In the meantime, you could try fitting less data at first and then gradually fit more data (I can give more guidance on this if you like).

Bryan
________________________________
From: Yu Fu ***@***.***>
Sent: Wednesday, June 21, 2023 5:33:48 PM
To: EmoryUniversityTheoreticalBiophysics/SirIsaac ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EmoryUniversityTheoreticalBiophysics/SirIsaac] OverflowError: (34, 'Result too large') (Issue #31)


Hi, Professor Daniels,

I am trying to perform modelling mRMA network data with sigmoidal class. I created a fitting problem with 100 data point, after I run my program at terminal for approximately 100 minutes, the program ended with an overflow error:

***STDERR***
b"<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n<string>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?\n"
localFitParallel: worker 1 working on work_array 0...
localFitParallel: worker 6 working on work_array 5...
localFitParallel: worker 7 working on work_array 6...
localFitParallel: worker 3 working on work_array 2...
localFitParallel: worker 8 working on work_array 7...
localFitParallel: worker 4 working on work_array 3...
localFitParallel: worker 9 working on work_array 8...
localFitParallel: worker 2 working on work_array 1...
WARNING:ReactionNetworks.Components:Failed to import dynamically compiled C module CTSN_0_wirelessprv_10_194_237_143_near_illinois_edu_78849_8762937861_48443 for network CTSN.
WARNING:ReactionNetworks.Components:No module named 'CTSN_0_wirelessprv_10_194_237_143_near_illinois_edu_78849_8762937861_48443'
localFitParallel: worker 5 working on work_array 4...
capi_return is NULL
Call-back cb_jac_in_daskr__user__routines failed.
Fatal Python error: F2PySwapThreadLocalCallbackPtr: PyLong_AsVoidPtr failed
Python runtime state: initialized
Traceback (most recent call last):
  File "<string>", line 6, in ddaskr_jac
  File "<string>", line 38, in dres_dc_function
OverflowError: (34, 'Result too large')

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 48442 RUNNING AT wirelessprv-10-194-237-143.near.illinois.edu
=   EXIT CODE: 6
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Abort trap: 6 (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

Traceback (most recent call last):
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fittingProblem.py", line 1823, in localFitToData_parallel
    output = load(outputFilename)
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/simplePickle.py", line 24, in load
    fin = io.open(filename,'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'temporary_94132_localFitToData_parallel_output.data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/penguinaugustus/Desktop/mrna_sig_terminal/mRNA-sigm.py", line 195, in <module>
    p.fitAll()
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fittingProblem.py", line 979, in fitAll
    FittingProblem.fitAll(self,**kwargs)
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fittingProblem.py", line 216, in fitAll
    fittingModel.fitToData(self.fittingData,self.indepParamsList,         \
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fittingProblem.py", line 1720, in fitToData
    outputDict = self.localFitToData_parallel(self.numprocs,fittingData,
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fittingProblem.py", line 1832, in localFitToData_parallel
    raise Exception("localFitToData_parallel:"                            \
Exception: localFitToData_parallel: error in localFitParallel.py

########### EXT COMPILER OPTIMIZATION ###########
Platform      :
  Architecture: x64
  Compiler    : gcc

CPU baseline  :
  Requested   : 'min'
  Enabled     : SSE SSE2 SSE3
  Flags       : -msse -msse2 -msse3
  Extra checks: none

CPU dispatch  :
  Requested   : 'max -xop -fma4'
  Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
  Generated   : none
CCompilerOpt._cache_write[796] : write cache to path -> /Users/penguinaugustus/Desktop/mrna_sig_terminal/build/temp.macosx-10.9-x86_64-3.8/ccompiler_opt_cache_ext.py



Could you give me any hint on what may go wrong and how to fix it?

Thank you for your time!

Sincerely,
Yu

**Comment by penguinaugustus** [comment]
Professor Daniels,
Thank you so much! I will try to look at temporary_94132_localFitToData_parallel_stdout.txt and try fitting less data first. I am also looking forward to your guidance at your convenience. Wish you a pleasant travel :) 
Sincerely, 
Yu

**Comment by bcdaniels** [comment]
Yes, it looks like you are at least getting the fits to run when you start with less data.  The quality of the predictions that you're seeing is not that unusual for a small amount of data (though I'm surprised maybe that the residuals all have the same sign).

To gradually add data and refit, you can pass in the fit parameters from a previous fit (in this case, a fit to a smaller amount of data) using the `smallerBestParamsDict` kwarg when you initialize fitting problems.  This will use the previously fit parameters as a starting point, which tends to make the optimization work more consistently.  

Maybe the easiest way to do this is to use the machinery found in `SirIsaac.fitAllParallel`, which automatically sets up a series of fitting problems with increasing amounts of data — see the documentation for `fitAllParallel.initializeFitAllParallel`, e.g. here: https://github.com/EmoryUniversityTheoreticalBiophysics/SirIsaac/blob/84f35c3734e3b51bcb348f50dc009c207b6d6ccc/SirIsaac/fitAllParallel.py#L442

If you run into more problems, feel free to message me again.  As a (more complicated) example, you can also take a look at the code we used for fitting behavioral data here (e.g. in `initializeWormFitting.py`): 
https://figshare.com/articles/Data_and_Code_Archive_for_Automated_predictive_and_interpretable_inference_of_C_elegans_escape_dynamics_/7806602

**Comment by penguinaugustus** [comment]
Hi Professor Daniels,
Thank you so much for your further instruction!

For the residuals problem, i guess it is because my totalsteps and ensTemperature is low: `totalSteps = 20 #1e3 ` `ensTemperature= 40`. 

I read the documentation for fitAllParallel.initializeFitAllParallel and the example of C elegans behavior and tries to apply the machinery on my problem. However, I still feel a little bit confused on how to run it. Here is where I am:

In my first script `mRNA-sigmoidal-litt.py`,  i first generate simulation data for the fitting problem and create problem:
```
p = fittingProblem.CTSNFittingProblem( complexityList, 
    sirIsaacData[:N], indepParamsList=indepParamsList[:N], 
    outputNames=outputNames, indepParamNames=indepParamNames, 
    ensGen=ensGen, avegtol=avegtol, maxiter=maxiter,
    priorSigma=priorSigma, numprocs=numprocs, verbose=True )
```
Then i use initializeFitAllParallel like this: 
```
initializeFitAllParallel(p,prefix,maxTimesPerIndepParam=maxTimesPerIndepParam,
                         deltaNumDatapoints=deltaNumDatapoints)
```

here i am not sure how to create prefix. So I just imitate what initializeWormFitting.py did: add the following code in front of `initializeFitAllParallel`
```
####### copied from the file initializeWormFitting.py
outputDirectory = '.'
if len(sys.argv) < 2:
    prefix = nextFileNumString(outputDirectory)
elif (sys.argv[1].find('&') != -1) or (sys.argv[1].find('>') != -1)         \
    or (sys.argv[1].find('|') != -1):
    prefix = nextFileNumString(outputDirectory)
else:
    prefix = sys.argv[1]
```

```
##### copied from initializeWormFitting.py
fileNumString = prefix
print("initializeWormFitting: Output files will start with %s"%(fileNumString))
configString = '_fitProb_varying_numInputs'                                 \
   +'_mRNAData'                                                             \
   +'_CTSN'                                                                 \
   +'_withEnsembleT'+str(int(ensTemperature))                               \
   +'_steps'+str(totalSteps)                             \
   +'_maxiter'+str(maxiter)                                                 \
   +'_avegtol'+str(avegtol)                                                 
saveFilename = fileNumString+configString+'.dat'
```
Then i run `mRNA-sigmoidal-litt.py`, the terminal output was: 
```
(base) penguindeMacBook-Pro:SirIsaac penguinaugustus$ python mRNA-sigmoidal-litt.py
initializeWormFitting: Output files will start with 0005
initializeFitAllParallel: Done initializing N = 2
```
Then I create another script called `runWormFitting.py` to run the inference procedure (adapted from the C elegans example):
```
import sys, os
from SirIsaac.fitAllParallel import runFitAllParallelWorker 

endTimeHours = None

if __name__ == '__main__':
    
    # index of the fitting problem database file is set by command-line argument
    if len(sys.argv) < 2 or len(sys.argv) > 2:
        print("Usage: python runWormFitting.py [fileNumString]")
        exit()
    else:
        fileNumString = sys.argv[1]
    
    print("runWormFitting: This computer's name is %s"%(os.uname()[1]))

    runFitAllParallelWorker(fileNumString,endTime=endTimeHours)
```
here i am not sure what is `fileNumString`. I guess it could be an int. Then i tried to run it with `python runWormFitting.py 1` and i go output like this: 
```
(base) penguindeMacBook-Pro:SirIsaac penguinaugustus$ python runWormFitting.py 1
runWormFitting: This computer's name is wirelessprv-10-194-237-143.near.illinois.edu
Traceback (most recent call last):
  File "runWormFitting.py", line 17, in <module>
    runFitAllParallelWorker(fileNumString,endTime=endTimeHours)
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fitAllParallel.py", line 586, in runFitAllParallelWorker
    raise Exception("fitProbData database file not found: "+str(fitProbDatFilename))
NameError: name 'fitProbDatFilename' is not defined
```

Sorry for writing a rather lengthy question. Thank you for any kind of instruction!

Sincerely,
Yu

**Comment by bcdaniels** [comment]
Yes, looks like you're on the right track.  Sorry that this part of the code is not documented very well yet!

The whole "`prefix`" and "`fileNumString`" business is just a way to keep files from different runs of `initializeFitAllParallel` distinct.  When you run `initializeFitAllParallel`, you can give it any string for the `fileNumString` argument, and it will add that string to the beginning of all the files it creates.  By default, the bit you copied from `initializeWormFitting.py` will set `fileNumString` to something like `0005` (with the lowest number possible that doesn't overwrite existing files).  Alternately, you can run the file with an additional argument to set the prefix (e.g. `python mRNA-sigmoidal-litt.py myFavoritePrefix`).  Then when you run `runWormFitting.py`, you give it the prefix of the data files that you want to use (e.g. `python runWormFitting.py 0005` or `python runWormFitting.py myFavoritePrefix`).

The weird error message was a typo in `SirIsaac.fitAllParallel` that should now be fixed if you reinstall.  (The code should have raised an exception that said `fitProbData database file not found: 1_fitProbData.dat`)

**Comment by penguinaugustus** [comment]
Thank you so much for your explaination on `prefix` ! It makes sense to me now!
Is it true that the workflow would be  
1. run initializeFitAllParallel and generate file `0001_fitProbs.dat` and the file stores parameter fit with the first `n` datapoints
2. run `python runWormFitting.py 0001` 
repeat the process until we have add enough data to the process.

In addition, i meet another problem when i run `python runWormFitting.py 0001` . It seems that `saveFilename` is `'NoneType'`😭
```
(base) wirelessprv-10-194-237-143:SirIsaac penguinaugustus$ python runWormFitting.py 0001
runWormFitting: This computer's name is wirelessprv-10-194-237-143.near.illinois.edu
0001_fitProbs/N2/condition0/
<class 'NoneType'>
Traceback (most recent call last):
  File "runWormFitting.py", line 17, in <module>
    runFitAllParallelWorker(fileNumString,endTime=endTimeHours)
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fitAllParallel.py", line 602, in runFitAllParallelWorker
    fitProb = loadFitProb(saveFilename,fileNumString,conditioni,numTimepoints)
  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fitAllParallel.py", line 45, in loadFitProb
    return load(dirPrefix+saveFilename)[numTimepoints]
TypeError: can only concatenate str (not "NoneType") to str
```
Thank you so much for your time.

**Comment by bcdaniels** [comment]
Yes, that’s the way to run fitting for the `fitProbs` file.  The idea, though, is that one `fitProbs` file itself contains copies of fitting problems with datasets of increasing size.

The `saveFilename` issue should be solved by including the argument `saveFilename=` in your original call to `fittingProblem.CTSNFittingProblem`, giving it any string to be used in the file name.  (This is technically a bug because the `saveFilename` shouldn’t be required, but this is the easiest workaround for the moment.)

From: Yu Fu ***@***.***>
Date: Thursday, July 6, 2023 at 10:14 AM
To: EmoryUniversityTheoreticalBiophysics/SirIsaac ***@***.***>
Cc: BRYAN DANIELS ***@***.***>, Comment ***@***.***>
Subject: Re: [EmoryUniversityTheoreticalBiophysics/SirIsaac] OverflowError: (34, 'Result too large') (Issue #31)

Thank you so much for your explaination on prefix ! It makes sense to me now!
Is it true that the workflow would be

  1.  run initializeFitAllParallel and generate file 0001_fitProbs.dat and the file stores parameter fit with the first n datapoints
  2.  run python runWormFitting.py 0001
repeat the process until we have add enough data to the process.

In addition, i meet another problem when i run python runWormFitting.py 0001 . It seems that saveFilename is 'NoneType'😭

(base) wirelessprv-10-194-237-143:SirIsaac penguinaugustus$ python runWormFitting.py 0001

runWormFitting: This computer's name is wirelessprv-10-194-237-143.near.illinois.edu

0001_fitProbs/N2/condition0/

<class 'NoneType'>

Traceback (most recent call last):

  File "runWormFitting.py", line 17, in <module>

    runFitAllParallelWorker(fileNumString,endTime=endTimeHours)

  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fitAllParallel.py", line 602, in runFitAllParallelWorker

    fitProb = loadFitProb(saveFilename,fileNumString,conditioni,numTimepoints)

  File "/Users/penguinaugustus/SirIsaac/SirIsaac/fitAllParallel.py", line 45, in loadFitProb

    return load(dirPrefix+saveFilename)[numTimepoints]

TypeError: can only concatenate str (not "NoneType") to str

Thank you so much for your time.

**Comment by penguinaugustus** [comment]
Thank you so much for your reply! I will think about it and try to fix the bug!
